version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "80:80"
    volumes:
      - ./dist/browser:/var/www/html
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
